# Generated by Django 5.1.4 on 2025-01-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(choices=[('JACKETS | COATS', 'JACKETS | COATS'), ('SWEATSHIRTS | KNITWEAR', 'SWEATSHIRTS | KNITWEAR'), ('SHIRTS', 'SHIRTS'), ('SHOES', 'SHOES'), ('T-SHIRTS | POLO SHIRTS', 'T-SHIRTS | POLO SHIRTS'), ('DRESSES', 'DRESSES'), ('TOPS', 'TOPS'), ('BOTTOMS', 'BOTTOMS'), ('SKIRTS', 'SKIRTS'), ('PANTS', 'PANTS'), ('JEANS', 'JEANS'), ('OTHER', 'OTHER')], default='OTHER', max_length=50)),
                ('product_item', models.TextField(max_length=100)),
                ('product_size', models.CharField(choices=[('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XS', 'Extra Small')], default='M', max_length=5)),
                ('product_color', models.TextField(max_length=30)),
                ('product_brand', models.TextField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_releasing_year', models.PositiveIntegerField(default=2023)),
            ],
        ),
    ]
